### ISSUE TITLE
Been trying for weeks

### ISSUE THREAD

**Issue by ghost** [koenhendriks/YifyAPI#4]
I've been trying for weeks to extract data based on the IMB code.
My current attempt:
		$json = file_get_contents('https://yts.ag/api/v2/list_movies.json?query_term='.$row['IMB'].'');
		$YTS_obj = json_decode($json);
		echo "YTS id: ".$YTS_obj->id[0];

I have the IMB code so that is not it. Please email me with suggestions?

**Comment by koenhendriks** [comment]
Hello there,

I'm not sure what you are trying to achieve here, as your example is not using the wrapper this repository represents.

If you are just trying to get the movie object from the YTS api you can use it like this:


```php
<?php

$imdbCode = 'tt0137523';
$ytsResponse = file_get_contents('https://yts.ag/api/v2/list_movies.json?query_term='.$imdbCode);

$ytsObject = json_decode($ytsResponse,1);
$movies = $ytsObject['data']['movies'];

foreach ($movies as $movie) {
	echo $movie['title'].' has IMDB: '.$movie['imdb_code'];
	echo '<br/> '.$movie['summary'].'<br/><hr/>';
}
```

I used a for-each loop even though the IMDB code is unique. I did this because you can use the same code for multiple movies if you update the query term in the YTS URL.

If you want support for IMDB search in this wrapper you can easily extend it if you look at the constructor parameters. You can fork this repository and make a pull request once you've done so. I'll be happy to merge it.

**Comment by ghost** [comment]
Thank you so much, your example pointed me in the RIGHT direction :-) I am getting MASSIVE data that I was missing before. My next trick is to get the older data like records 1-5000. Lots of missing info yet, they are up to 6,816 but I have a lot of missing IDs. Thank you again for your help.
